"""Generates direwolf.conf from the application config."""

import yaml
from pathlib import Path


def calculate_passcode(callsign: str) -> int:
    """Calculate APRS-IS passcode from callsign (official algorithm)."""
    call = callsign.upper().split("-")[0]
    code = 0x73E2
    for i, char in enumerate(call):
        if i % 2 == 0:
            code ^= ord(char) << 8
        else:
            code ^= ord(char)
    return code & 0x7FFF


def validate(config: dict) -> list[str]:
    """
    Return a list of validation error strings.
    Empty list means the config is valid.
    """
    errors = []

    def _check_location(label: str, loc: dict) -> None:
        if loc.get("source") != "fixed":
            return
        lat = loc.get("latitude")
        lon = loc.get("longitude")
        if lat is None or not (-90 <= lat <= 90):
            errors.append(f"{label}: latitude must be between -90 and 90 (got {lat!r})")
        if lon is None or not (-180 <= lon <= 180):
            errors.append(f"{label}: longitude must be between -180 and 180 (got {lon!r})")

    rb = config.get("rf_beacon", {})
    if rb.get("enabled"):
        _check_location("RF beacon", rb.get("location", {}))

    ib = config.get("igate_beacon", {})
    if ib.get("enabled"):
        _check_location("Igate beacon", ib.get("location", {}))

    mode = config.get("mode", {})
    rx_only = mode.get("rx_only", True)
    igate_enabled = mode.get("igate", False) and not rx_only
    igate_beacon_enabled = not rx_only and ib.get("enabled", False)

    if mode.get("digipeater") and not rx_only:
        if not config.get("digipeater", {}).get("aliases"):
            errors.append("Digipeater enabled but no aliases selected")
        sf = config.get("digipeater", {}).get("source_filter", [])
        if not isinstance(sf, list):
            errors.append("Digipeater: source_filter must be a list")
        elif any(not isinstance(p, str) or not p.strip() for p in sf):
            errors.append("Digipeater: source_filter entries must be non-empty strings")

    if igate_enabled or igate_beacon_enabled:
        port = config.get("igate", {}).get("port", 14580)
        if not isinstance(port, int) or not (1 <= port <= 65535):
            errors.append(f"Igate: port must be 1-65535 (got {port!r})")

    aging = config.get("map", {}).get("station_aging")
    if aging is not None:
        if not isinstance(aging, int) or aging < 0:
            errors.append(
                f"Map: station_aging must be a non-negative integer (got {aging!r})"
            )

    return errors


def generate(config: dict) -> str:
    """Build direwolf.conf content from config dict. Returns the file as a string."""
    lines = []

    def line(s=""):
        lines.append(s)

    callsign = config.get("callsign", "NOCALL")
    ssid = config.get("ssid", 0)
    station = f"{callsign}-{ssid}" if ssid else callsign

    mode = config.get("mode", {})
    rx_only = mode.get("rx_only", True)
    igate_enabled = mode.get("igate", False) and not rx_only
    digipeat_enabled = mode.get("digipeater", False) and not rx_only
    igate_beacon_enabled = not rx_only and config.get("igate_beacon", {}).get("enabled", False)

    iface = config.get("interface", {})
    ptt = config.get("ptt", {})
    hw = config.get("hardware", {})

    # ── Header ────────────────────────────────
    line("# direwolf.conf — generated by APRS Digipeater")
    line("# Do not edit manually — changes will be overwritten.")
    line()

    # ── Callsign ──────────────────────────────
    line(f"MYCALL {station}")
    line()

    # ── Audio / Interface ─────────────────────
    if iface.get("type") == "serial":
        line(f"ADEVICE {iface.get('device', '/dev/ttyUSB0')}")
        line(f"# Baud rate for serial TNC: {iface.get('baud', 9600)}")
    else:
        audio_in = iface.get("audio_input", "default")
        audio_out = iface.get("audio_output", "default")
        line(f"ADEVICE {audio_in} {audio_out}")

    line("ARATE 44100")
    line("CHANNEL 0")
    line()

    # ── Modem ─────────────────────────────────
    line("MODEM 1200")
    line()

    # ── GPSD (live GPS for beacons) ───────────
    _needs_gpsd = (
        (not rx_only and config.get("rf_beacon", {}).get("enabled") and
         config.get("rf_beacon", {}).get("location", {}).get("source") == "gps")
        or
        (igate_beacon_enabled and
         config.get("igate_beacon", {}).get("location", {}).get("source") == "gps")
    )
    if _needs_gpsd:
        line("GPSD")
        line()

    # ── PTT ───────────────────────────────────
    if not rx_only:
        method = ptt.get("method", "gpio")
        if method == "gpio":
            line(f"PTT GPIO {ptt.get('pin', 17)}")
        elif method == "serial_rts":
            line(f"PTT {ptt.get('port', '/dev/ttyUSB0')} RTS")
        elif method == "serial_dtr":
            line(f"PTT {ptt.get('port', '/dev/ttyUSB0')} DTR")
        elif method == "cm108":
            line("PTT CM108")
        elif method == "vox":
            line("PTT VOX")
        line()

    # ── Digipeater ────────────────────────────
    if digipeat_enabled:
        aliases = config.get("digipeater", {}).get("aliases", ["WIDE1-1", "WIDE2-1"])
        for alias in aliases:
            line(f"DIGIPEAT 0 0 ^WIDE[3-7]-[1-7]$ ^{alias}$ TRACE")
        sf = [str(p).upper().strip() for p in config.get("digipeater", {}).get("source_filter", []) if str(p).strip()]
        if sf:
            line(f"FILTER 0 0 b/{'/'.join(sf)}")
        line()

    # ── Igate ─────────────────────────────────
    if igate_enabled or igate_beacon_enabled:
        ig = config.get("igate", {})
        _pc = config.get("aprs_passcode")
        passcode = _pc if _pc not in ("", None) else calculate_passcode(callsign)
        line(f"IGSERVER {ig.get('server', 'rotate.aprs2.net')}")
        line(f"IGPORT {ig.get('port', 14580)}")
        line(f"IGLOGIN {callsign} {passcode}")
        if igate_enabled and ig.get("filter"):
            line(f"IGFILTER {ig['filter']}")
        line()

    # ── RF Beacon ─────────────────────────────
    rb = config.get("rf_beacon", {})
    if not rx_only and rb.get("enabled"):
        loc = rb.get("location", {})
        pos = _beacon_pos(loc)
        line(
            f"{rb.get('type', 'PBEACON')} "
            f"DELAY={rb.get('delay', 1)} "
            f"EVERY={rb.get('every', 30)} "
            f"OVERLAY={rb.get('overlay', 'S')} "
            f"SYMBOL={rb.get('symbol', '#')} "
            f"{pos}"
            f"COMMENT=\"{rb.get('comment', 'Digipeater')}\""
        )
        line()

    # ── Igate Beacon ──────────────────────────
    if igate_beacon_enabled:
        ib = config.get("igate_beacon", {})
        loc = ib.get("location", {})
        pos = _beacon_pos(loc)
        line(
            f"{ib.get('type', 'PBEACON')} "
            f"SENDTO=IG "
            f"DELAY={ib.get('delay', 1)} "
            f"EVERY={ib.get('every', 30)} "
            f"OVERLAY={ib.get('overlay', 'S')} "
            f"SYMBOL={ib.get('symbol', '#')} "
            f"{pos}"
            f"COMMENT=\"{ib.get('comment', 'Digipeater')}\""
        )
        line()

    return "\n".join(lines)


def write(config: dict, path: str = None) -> None:
    """Write direwolf.conf to disk."""
    output_path = Path(path or config.get("direwolf", {}).get("config_path", "/etc/direwolf/direwolf.conf"))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate(config))


def load_config(path: str = "config.yaml") -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def _beacon_pos(loc: dict) -> str:
    """Return the position portion of a PBEACON line.
    GPS source: empty string — Direwolf reads position from gpsd.
    Fixed source: 'LAT ddmm.mmN LONG dddmm.mmE ' (trailing space included).
    """
    if loc.get("source") == "fixed":
        lat = _format_lat(loc.get("latitude", 0))
        lon = _format_lon(loc.get("longitude", 0))
        return f"LAT {lat} LONG {lon} "
    return ""  # gpsd supplies position automatically


def _format_lat(lat: float) -> str:
    """Convert decimal degrees latitude to APRS format (DDMM.MMN/S)."""
    hemi = "N" if lat >= 0 else "S"
    lat = abs(lat)
    deg = int(lat)
    mins = (lat - deg) * 60
    return f"{deg:02d}{mins:05.2f}{hemi}"


def _format_lon(lon: float) -> str:
    """Convert decimal degrees longitude to APRS format (DDDMM.MME/W)."""
    hemi = "E" if lon >= 0 else "W"
    lon = abs(lon)
    deg = int(lon)
    mins = (lon - deg) * 60
    return f"{deg:03d}{mins:05.2f}{hemi}"
